# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DevOps pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run test job'
        required: true
        type: boolean
      version:
        description: 'Run build and deploy image job'
        required: True
        type: boolean

permissions:
  contents: read

env:
  docker_username: ${{secrets.DOCKER_simon_USERNAME}}
  docker_password: ${{secrets.DOCKER_simon_PASSWORD}}
  API_KEY: ${{secrets.API_KEY}}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest
  
  build_image:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: docker login -u $docker_username -p $docker_password
    - name: Build the Docker image
      run: docker build -t simontroedsson/demo:1.1 .
    - name: Push image to dockerhub
      run: docker push simontroedsson/demo:1.1

      
  deploy_image:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - uses: actions/checkout@v4
    
