# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DevOps pipeline

on:
  workflow_dispatch:
    inputs:
      run_test_job:
        description: 'Run test job'
        required: true
        type: boolean
        default: false
      run_build_deploy_image_job:
        description: 'Run build and deploy image job'
        required: True
        type: boolean
        default: false

permissions:
  contents: read

env:
  docker_username: ${{secrets.DOCKER_simon_USERNAME}}
  docker_password: ${{secrets.DOCKER_simon_PASSWORD}}
  API_KEY: ${{secrets.API_KEY}}
  

jobs:
  test:
    if: ${{ github.event.inputs.run_test_job || (github.event.inputs.run_test_job == false && github.event.inputs.run_build_deploy_image_job == false) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
      continue-on-error: true
      if: ${{inputs.run_test_job == true}}
    - name: test
      run: echo test
  
  build_deploy_image:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event.inputs.run_build_deploy_image_job || (github.event.inputs.run_test_job == false && github.event.inputs.run_build_deploy_image_job == false) }}
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: docker login -u $docker_username -p $docker_password
    - name: Build the Docker image
      run: docker build -t simontroedsson/demo:1.1 .
    - name: Push image to dockerhub
      run: docker push simontroedsson/demo:1.1


    
