name: Docker Image CI

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_JASMIN_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_JASMIN_PASSWORD }}
  IMAGE_NAME: "${{ secrets.DOCKER_JASMIN_USERNAME }}/pingvin_app:latest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
  run-tests:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set environment variables
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
  
      - name: Run tests
        run: python -m pytest
        
  build:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:

      - name: Create dockerfile
        run: |
          echo -e "FROM python:3.9\nCOPY . /app/\nWORKDIR /app\nRUN pip install -r requirements.txt\nCMD ['python', 'app.py']" > Dockerfile
  
      - name: Build the Docker image
        run: docker build -t "$IMAGE_NAME" .
        
  publish:
      runs-on: ubuntu-latest
      needs: build
      steps:
    
      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
      - name: Push the Docker image to Docker Hub
        run: docker push "$IMAGE_NAME"
